### ISSUE TITLE
Factor 17.5 too long for vTaskDelay()

### ISSUE THREAD

**Issue by DavidBerweiler** [feilipu/miniAVRfreeRTOS#8]
I tried to get the miniAVRfreeRTOS running on a ATMega1284P with a minimal reproducable example, see the following:
    

    #define F_CPU 11095200
    #define TIMER_FACTOR 17.5
    #include "FreeRTOS.h"
    #include "task.h"
    #include <xc.h>
    
    void TestTask(void* param){
	    while(1)
	    {
		    (void)param;
		    PORTB ^= 0xFF;
		    vTaskDelay(1000./TIMER_FACTOR);
	    }
    }
    
    int main(void)
    {
	    DDRB = 0xFF;
	    PORTB = 0xFF;
	    xTaskCreate(TestTask, "Test", 200, NULL, tskIDLE_PRIORITY + 1, NULL);
				    
    vTaskStartScheduler();
        while(1)
        {
        }
    }

For some unclear reason the vTaskDelay and vTaskDelayUntil seem to wait for 17.5 times the given amount. Might there be any particular reason for this issue? I am using a [AVR364: MEGA1284P xPlained](http://ww1.microchip.com/downloads/en/DeviceDoc/doc8377.pdf)

**Comment by feilipu** [comment]
Remember [`vTaskDelay()`](https://www.freertos.org/a00127.html) is measuring Ticks, not milliseconds. The `WDT` driven Scheduler should produce 15ms Ticks ([very approximate within 20%](https://github.com/feilipu/Arduino_FreeRTOS_Library/blob/master/doc/tick_sources.md#wdt-precision-limitations)), and 17.5ms Ticks would be within the specification.

I would [check the fuses ](https://www.engbedded.com/fusecalc/) to ensure that the FCPU value that you're using (based on the physical crystal) is correctly operating. Especially check that the full swing oscillator is selected, as the AT1284P device is sensitive (i.e. doesn't work with) with the Crystal Oscillator settings.

Otherwise, I can't imagine any reason why it would not be working correctly. Perhaps have a look at the configuration for the [Goldilocks Analogue](https://github.com/feilipu/Arduino_Goldilocks_Variant)? Although that uses a different FCPU, but look in particular at the [`boards.txt`](https://github.com/feilipu/Arduino_Goldilocks_Variant/blob/master/boards.txt) file containing fuse settings.
